#pragma once

#include "Geometry/Curves/BezierCurve.h"
#include "Geometry/Curves/BSpline.h"
#include "Geometry/Curves/Curve.h"
#include "Geometry/Curves/FunctionCurve.h"
#include "Geometry/Curves/HermiteSpline.h"
#include "Geometry/Curves/LagrangeCurve.h"
#include "Geometry/Curves/NURBS.h"

#include "Geometry/Meshes/Arrow.h"
#include "Geometry/Meshes/Cone.h"
#include "Geometry/Meshes/Cube.h"
#include "Geometry/Meshes/Cuboid.h"
#include "Geometry/Meshes/Cylinder.h"
#include "Geometry/Meshes/Frustum.h"
#include "Geometry/Meshes/Mesh.h"
#include "Geometry/Meshes/Points.h"
#include "Geometry/Meshes/Polygon.h"
#include "Geometry/Meshes/RoundedCube.h"
#include "Geometry/Meshes/Shell.h"
#include "Geometry/Meshes/Sphere.h"
#include "Geometry/Meshes/SphereSector.h"
#include "Geometry/Meshes/SphereSegment.h"
#include "Geometry/Meshes/SphereWedge.h"
#include "Geometry/Meshes/Torus.h"
#include "Geometry/Meshes/Tube.h"
