#pragma once

#include "Scene/Animations/Animation.h"
#include "Scene/Animations/CurveAnimation.h"
#include "Scene/Animations/Easing.h"
#include "Scene/Animations/KeyframeAnimation.h"
#include "Scene/Animations/Orbiting.h"
#include "Scene/Animations/Rotation.h"
#include "Scene/Animations/Scaling.h"
#include "Scene/Animations/Translation.h"

#include "Scene/Lights/AmbientLight.h"
#include "Scene/Lights/AmbientLightBuilder.h"
#include "Scene/Lights/DirectionalLight.h"
#include "Scene/Lights/DirectionalLightBuilder.h"
#include "Scene/Lights/Light.h"
#include "Scene/Lights/LightBuilder.h"
#include "Scene/Lights/PositionalLight.h"
#include "Scene/Lights/PositionalLightBuilder.h"
#include "Scene/Lights/SpotLight.h"
#include "Scene/Lights/SpotLightBuilder.h"

#include "Scene/Transforms/Rotate.h"
#include "Scene/Transforms/Scale.h"
#include "Scene/Transforms/Transform.h"
#include "Scene/Transforms/Translate.h"

#include "Scene/SceneNodes/AnimationNode.h"
#include "Scene/SceneNodes/Group.h"
#include "Scene/SceneNodes/LightUnit.h"
#include "Scene/SceneNodes/LightUnitBuilder.h"
#include "Scene/SceneNodes/Model.h"
#include "Scene/SceneNodes/ModelBuilder.h"
#include "Scene/SceneNodes/RenderUnit.h"
#include "Scene/SceneNodes/RenderUnitBuilder.h"
#include "Scene/SceneNodes/Scene.h"
#include "Scene/SceneNodes/SceneNode.h"
#include "Scene/SceneNodes/SceneNodeBuilder.h"
#include "Scene/SceneNodes/TransformNode.h"
#include "Scene/SceneNodes/TransformNodeBuilder.h"
